theme = "dracula"

# esc
[keys.insert.j]
k = "normal_mode"

[keys.normal]
# s = "search"
# C-R redo
C-R = "redo"

# Muscle memory
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
G = "goto_file_end"
"%" = "match_brackets"
V = ["select_mode", "extend_to_line_bounds"]
C = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
D = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]
S = "surround_add" # Would be nice to be able to do something after this but it isn't chainable

# write/quit
[keys.normal.Z]
Z = ":write-quit"
Q = ":quit"

[keys.normal."space"]
# write
w = ":write"
# edit
e = { c = ":open ~/.config/helix/config.toml" }

